// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urygiypelicgfollbmvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyeWdpeXBlbGljZ2ZvbGxibXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTM2MTgsImV4cCI6MjA2MDM2OTYxOH0.x6IcH53wMtCUtiKVZs366AXdKcwd4QnAW_3MvCPOiPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);